name: Build Flutter Example

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            name: linux
          - os: macos-latest
            name: macos
          - os: windows-latest
            name: windows
    
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: example

    steps:
    - uses: actions/checkout@v4

    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        cache: true

    - name: Install Linux dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev


    - name: Get Flutter dependencies
      run: flutter pub get

    - name: Build Flutter debug app
      run: flutter build ${{ matrix.name }} --debug

    - name: Where is the build?
      if: failure() && matrix.os == 'windows-latest'
      shell: pwsh
      run: |
        Get-ChildItem -Path . -Filter open62541.lib -Recurse

    - name: Build Flutter release app
      run: flutter build ${{ matrix.name }} --release

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: flutter-app-${{ matrix.name }}
        path: example/build/${{ matrix.name }}/
