name: Build Flutter Example

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: build-${{ matrix.name }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            name: linux
            target: linux
          - os: macos-latest
            name: macos
            target: macos
          - os: windows-latest
            name: windows
            target: windows
          - os: macos-latest
            name: ios
            target: ios
          - os: ubuntu-latest
            name: android
            target: apk
    
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: example

    steps:
    - uses: actions/checkout@v4

    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        cache: true

    - name: Install Linux dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev

    - name: Get Flutter dependencies
      run: flutter pub get

    - name: Build Flutter debug app
      run: flutter build ${{ matrix.target }} --debug --no-codesign
      if: matrix.target == 'ios'

    - name: Build Flutter debug app
      run: flutter build ${{ matrix.target }} --debug
      if: matrix.target != 'ios'

    - name: Where is the build?
      if: failure() && matrix.os == 'windows-latest'
      shell: pwsh
      run: |
        Get-ChildItem -Path . -Filter open62541.lib -Recurse

    - name: Build Flutter release app
      run: flutter build ${{ matrix.target }} --release --no-codesign
      if: matrix.target == 'ios'

    - name: Build Flutter release app
      run: flutter build ${{ matrix.target }} --release
      if: matrix.target != 'ios'

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: flutter-app-${{ matrix.name }}
        path: example/build/${{ matrix.target }}/
